version: '3'
services:
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./openvpn-status:/app/openvpn-status
      - /var/run/docker.sock:/var/run/docker.sock  # Monta o socket Docker
